# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x, 10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install react client
      working-directory: ./software/cloud-dashboard/react-client
      run: npm install 
    - name: install node server
      working-directory: ./software/cloud-dashboard/node-server
      run: npm install 
    - name: run react-client test
      working-directory: ./software/cloud-dashboard/react-client
      run: npm run test
    - name: run node-server test
      working-directory: ./software/cloud-dashboard/node-server
      run: npm run test -- --coverage
